### ISSUE TITLE
problem with activate ability - assert self.can_afford(action)

### ISSUE THREAD

**Issue by noxgle** [Dentosal/python-sc2#63] opened 2018-06-28 18:15 UTC
code:

forces3 = self.units(VIKINGFIGHTER)
for unit2 in forces3.idle:
                    await self.do(unit2(MORPH_VIKINGASSAULTMODE))

error:

 File "C:\Users\xxx\Desktop\sc2\piconAI1.py", line 641, in on_step
    await self.attack()
  File "C:\Users\xxx\Desktop\sc2\piconAI1.py", line 674, in attack
    await self.do(unit2(MORPH_VIKINGASSAULTMODE))
  File "C:\Users\xxx\AppData\Roaming\Python\Python36\site-packages\sc2\bot_ai.py", line 317, in do
  File "C:\Users\xxx\AppData\Roaming\Python\Python36\site-packages\sc2\bot_ai.py", line 317, in do
    assert self.can_afford(action)

I think it's bug

**Comment by Dentosal** [comment] 2018-07-10 15:58
Yes. Known issue, kind of.

Closing as a duplicate of #39.

**Closed by Dentosal** 2018-07-10 15:58 UTC
