### ISSUE TITLE
'A game has not been started yet'

### ISSUE THREAD

**Issue by Dobleman** [Dentosal/python-sc2#68] opened 2018-07-01 20:18 UTC
I am unable to run a game. It opens the black sc2 window as if it is loading the client, and then it closes after a couple seconds and I get this:

INFO:sc2.protocol:Client status changed to Status.launched (was None)
INFO:sc2.controller:Creating new game
INFO:sc2.controller:Map:     BelShirVestigeLE
INFO:sc2.controller:Players: Bot(Race.Zerg, <__main__.ZergBot object at 0x000001AB22610198>), Computer(Race.Terran, Difficulty.Easy)
INFO:sc2.protocol:Client status changed to Status.init_game (was Status.launched)
INFO:sc2.protocol:Client status changed to Status.launched (was None)
INFO:root:Player id: 0
INFO:sc2.sc2process:kill_switch: Process cleanup
INFO:sc2.sc2process:Cleaning up...
Traceback (most recent call last):
  File "D:/Games/StarCraft II/ai/sc2ai.py", line 14, in <module>
    ], realtime=True)
  File "C:\Users\Bobby\Anaconda3\lib\site-packages\sc2\main.py", line 187, in run_game
    _host_game(map_settings, players, **kwargs)
  File "C:\Users\Bobby\Anaconda3\lib\asyncio\base_events.py", line 468, in run_until_complete
    return future.result()
INFO:sc2.sc2process:Cleanup complete
  File "C:\Users\Bobby\Anaconda3\lib\site-packages\sc2\main.py", line 115, in _host_game
    result = await _play_game(players[0], client, realtime, portconfig, step_time_limit, game_time_limit)
  File "C:\Users\Bobby\Anaconda3\lib\site-packages\sc2\main.py", line 87, in _play_game
    result = await _play_game_ai(client, player_id, player.ai, realtime, step_time_limit, game_time_limit)
  File "C:\Users\Bobby\Anaconda3\lib\site-packages\sc2\main.py", line 29, in _play_game_ai
    game_data = await client.get_game_data()
  File "C:\Users\Bobby\Anaconda3\lib\site-packages\sc2\client.py", line 110, in get_game_data
    upgrade_id=True
  File "C:\Users\Bobby\Anaconda3\lib\site-packages\sc2\protocol.py", line 56, in _execute
    raise ProtocolError(f"{response.error}")
sc2.protocol.ProtocolError: ['A game has not been started yet']

**Comment by mjschuetze102** [comment] 2018-07-01 23:55
Same as #65

**Comment by Dentosal** [comment] 2018-07-15 22:24
Duplicate of #65. Please comment here if that doesn't work.

**Closed by Dentosal** 2018-07-15 22:24 UTC
