### ISSUE TITLE
Incorrect cost for Orbital Command upgrade (with fix)

### ISSUE THREAD

**Issue by Hannessa** [Dentosal/python-sc2#39] opened 2018-05-24 15:13 UTC
Seems like there's a known problem in the SC2 API where orbital command upgrade cost is counted as CC cost + upgrade cost, i.e. 550 minerals, although the upgrade itself is only 150. This messes up can_afford() and similar, because the cost appears to be much higher than it actually is. I've heard that the same goes for other building upgrades such as Lair, although I haven't looked into that yet.

I've created a quickfix/monkey patch for the orbital cost. It's basically a copy of GameData.calculate_ability_cost() with an adjustment for orbital upgrade. This can be added at the top of your bot script, but should probably be patched into the code base in the long run.
```
# Monky-patch for incorrect orbital cost
# TODO: Also fix other building upgrade costs
from sc2.game_data import GameData, AbilityData, Cost
from sc2.unit_command import UnitCommand
from sc2.ids.ability_id import AbilityId
from functools import lru_cache

@lru_cache(maxsize=256)
def calculate_ability_cost_fix(self, ability):
	if isinstance(ability, AbilityId):
		ability = self.abilities[ability.value]
	elif isinstance(ability, UnitCommand):
		ability = self.abilities[ability.ability.value]

	assert isinstance(ability, AbilityData), f"C: {ability}"

	for unit in self.units.values():
		if unit.creation_ability == ability:
			if ability.id == UPGRADETOORBITAL_ORBITALCOMMAND:
				# Orbital upgrades shouldn't cost 550 but 150
				return Cost(
					unit.cost.minerals - 400,
					unit.cost.vespene,
					unit.cost.time
				)
			if unit.id == ZERGLING:
				# HARD CODED: zerglings are generated in pairs
				return Cost(
					unit.cost.minerals * 2,
					unit.cost.vespene * 2,
					unit.cost.time
				)
			return unit.cost

	for upgrade in self.upgrades.values():
		if upgrade.research_ability == ability:
			return upgrade.cost

	return Cost(0, 0)

GameData.calculate_ability_cost = calculate_ability_cost_fix

```

**Comment by BurnySc2** [comment] 2018-05-25 15:40
I've noticed a similar issue with all zerg structures.
Using self.can_afford() on morphing buildings (hatchery -> lair, lair -> hive, spire -> greater spire) as well as on simple buildings (e.g. hatch, spawning pool, extractor), it will calculate the structure cost including the drone cost.

This is what self.can_afford() returns:
Spawning pool: 200 + 50 (drone) = 250 minerals
Extractor: 25 + 50 (drone) = 75 minerals
Lair: 50 (drone) + 300 (hatchery) + 150 + 100 gas = 500 minerals + 100 gas

Here are two screenshots with the lair morph attached, even though they don't show much except waiting for 500+ minerals before morphing.

Lair morph code:
```python
if self.can_afford(LAIR) and not self.already_pending(LAIR) and self.units(HATCHERY).ready.idle.exists and self.units(SPAWNINGPOOL).ready.exists and not self.units(LAIR).exists:
    err = await self.do(self.units(HATCHERY).ready.idle.first(UPGRADETOLAIR_LAIR))
```

![screenshot2018-05-25 17_35_01](https://user-images.githubusercontent.com/21288725/40553272-5ed7e0ca-6042-11e8-9573-eec22f8ec47e.jpg)
![screenshot2018-05-25 17_35_08](https://user-images.githubusercontent.com/21288725/40553275-611429de-6042-11e8-93f2-b64f88774a1b.jpg)

**Comment by Dentosal** [comment] 2018-05-31 09:29
I'm not sure if there is any way to fix this without either adding dependency trees, and then subtracting the costs, or just using a list of exceptions. There might not even exist a nice solution.

**Comment by Hannessa** [comment] 2018-05-31 09:51
I think it's okay to just hard-code the upgrade costs in sc2.game_data.GameData.calculate_ability_cost() until Blizzard fixes it in the API, like you did with the zerglings and I did with the orbital above. At least it fixes it for now.

Although it might be better to just set the final cost directly instead of subtracting, to make it easier to maintain, e.g.:
```
			if ability.id == UPGRADETOORBITAL_ORBITALCOMMAND:
				# Orbital Command upgrade
				return Cost(150, 0, unit.cost.time)
```

**Comment by Dentosal** [comment] 2018-05-31 10:34
The problem is that there are quite a lot of them. Problematic actions by type:

### Zerg building include drone cost

All drone-created Zerg buildings.

### Building upgrades (Terran / Zerg)

Lair, Hive, GreaterSpire, OrbitalCommand, PlanetaryFortress

### Zerg unit upgrades

Baneling, Lurker, BroodLord, MorphToOverseer, MorphtoOverlordTransport

### Free unit / building mode changes

SiegeMode, AssaultMode, UpgradeToWarpGate, Lower (supplydepot), HellionTank, VikingFighter, PhasingMode (warp prims), LiberatorAGMode, ...

### Misc

Some move commands, with ids 1835 and 1837

**Comment by Hannessa** [comment] 2018-05-31 10:57
Ah, I see, yeah that's annoying :/

Maybe it's better then to subtract the drone cost from the building etc.

**Comment by BurnySc2** [comment] 2018-07-28 21:49
Closing because this issue is mostly fixed in https://github.com/Dentosal/python-sc2/commit/084783534e3340baa4129dacacb156b3770ce023
Known issue: morph cost for units is still a problem (baneling, ravager, lurker, broodlord)

**Closed by BurnySc2** 2018-07-28 21:49 UTC
Labels: bug
